language: php

php:
- 5.5

env:
- WP_VERSION=nightly
- WP_VERSION=latest
- WP_VERSION=4.4.4

matrix:
  allow_failures:
    - env: WP_VERSION=nightly

before_install:
  - sudo apt-get update > /dev/null
  - composer self-update

  # Install Apache
  - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 php5-curl php5-mysql php5-intl
  - sudo a2enmod rewrite
  - export WORDPRESS_SITE_DIR=$(pwd)/www/
  - sudo sed -i -e "s,/var/www,$(pwd)/www,g" /etc/apache2/sites-available/default
  - sudo sed -i -e "s,AllowOverride None,AllowOverride All,g" /etc/apache2/sites-available/default
  - sudo sed -i -e "/DocumentRoot/i\ServerName wordpress.dev" /etc/apache2/sites-available/default
  - echo "127.0.0.1 wordpress.dev" | sudo tee -a /etc/hosts
  - sudo /etc/init.d/apache2 restart

install:

  # Build plugin
  - mkdir $(pwd)/build;
  - cp -r !(build) $(pwd)/build/

  # Install dependencies
  - composer update --no-interaction --prefer-dist;

  # install wordpress
  - bash ./ci/prepare.sh wordpress root '' localhost $WP_VERSION
  - mv ci/sample.htaccess ${WORDPRESS_SITE_DIR}.htaccess

  # start selenium
  - bash ./ci/pre-behat.sh
  - mkdir /tmp/mail/
  - chmod ugo+rwx /tmp/mail/
  - mkdir failed-scenerios/

before_script:

script:
  # Run unit tests.
  - vendor/bin/phpunit

  # Run behat tests.
  - vendor/bin/behat --tags=~@travis-flaky

  # Check coding standards.
  - vendor/bin/phpcs
